from pydantic import BaseModel, Field
from typing import Optional, List, Literal, Dict


# -------------------- Safety -------------------- #

class SafetyResult(BaseModel):
    """
    Result of the safety classifier.

    Matches usage in ai_nodes.safety_node:
    - risk: "none" | "self_harm" | "eating_disorder" | "severe_addiction" | "violence" | "other"
    - action: "allow" | "block_and_escalate"
    - message: short helper text
    """
    risk: Literal["none", "self_harm", "eating_disorder", "severe_addiction", "violence", "other"]
    action: Literal["allow", "block_and_escalate"]
    message: str


# -------------------- Quiz (MCQ) -------------------- #

class MCQOption(BaseModel):
    """
    One answer option for a multiple-choice question.
    """
    id: str = Field(
        ...,
        description="Stable identifier for the option, e.g. 'q1_a', 'q1_b'."
    )
    label: str = Field(
        ...,
        description="Short text shown to the user on the button / radio."
    )
    helper_text: Optional[str] = Field(
        default=None,
        description="Optional extra clarification for this specific option."
    )


class QuizQuestion(BaseModel):
    """
    One MCQ question in the AI-generated quiz.
    """
    id: str = Field(
        ...,
        description="Stable identifier for the question, e.g. 'q1', 'trigger', 'frequency'."
    )
    question: str = Field(
        ...,
        description="The exact question text to show the user."
    )
    helper_text: Optional[str] = Field(
        default=None,
        description="Optional short hint or example to clarify the question."
    )
    options: List[MCQOption] = Field(
        ...,
        description="Exactly 4 answer options for this question."
    )


class QuizForm(BaseModel):
    """
    The complete quiz generated by the AI for a specific habit.
    """
    habit_name_guess: str = Field(
        ...,
        description="Short guess of the habit name, based on the user's description."
    )
    questions: List[QuizQuestion] = Field(
        ...,
        description="8–10 tailored MCQ questions for this user's habit."
    )


class QuizSummary(BaseModel):
    """
    Compressed representation of the user's habit profile,
    derived from original description + quiz + answers.

    This is now a MECHANISTIC model, not just descriptive metadata.
    """

    # ---- Core identity & category ----
    user_habit_raw: str  # exact user wording
    canonical_habit_name: str  # clean, interpreted name (e.g. "nicotine pouches at work")

    habit_category: Optional[str] = Field(
        default=None,
        description=(
            "Broad but meaningful category, e.g. "
            "'nicotine_oral', 'pornography', 'social_media', "
            "'procrastination', 'alcohol', 'food_overeating', 'other'."
        ),
    )
    category_confidence: Literal["low", "medium", "high"] = "medium"

    product_type: Optional[str] = Field(
        default=None,
        description="More specific subtype where helpful, e.g. 'Zyn pouches', 'TikTok', 'cigars', 'late-night snacks'.",
    )

    severity_level: Literal["mild", "moderate", "severe"] = "mild"

    # ---- Mechanistic behaviour model (the important part) ----
    # These fields have defaults so validation doesn't fail if LLM can't provide them
    core_loop: str = Field(
        default="Habit loop not fully identified - requires more context.",
        description=(
            "One or two sentences summarizing the habit loop: "
            "trigger → thought → craving → action → reward → cost."
        ),
    )
    primary_payoff: str = Field(
        default="Emotional payoff unclear - likely relief or stimulation.",
        description="What the habit gives them emotionally (e.g. numbing, stimulation, belonging, avoiding shame).",
    )
    avoidance_target: str = Field(
        default="Avoidance target unclear - likely discomfort or boredom.",
        description="What the habit helps them avoid facing (e.g. failure, conflict, emptiness, performance anxiety).",
    )
    identity_link: str = Field(
        default="Identity link unclear - may see habit as coping mechanism.",
        description="How the habit ties into their identity or self-story (e.g. 'this is how I cope', 'my off-switch').",
    )
    dopamine_profile: str = Field(
        default="relief",
        description=(
            "Short summary of the reward type: stimulation / soothing / numbing / social reward / power / control."
        ),
    )
    collapse_condition: str = Field(
        default="Collapse condition unclear - likely during stress or boredom.",
        description=(
            "The scenario where their control usually fails (e.g. late-night alone, after conflict, during boredom)."
        ),
    )
    long_term_cost: str = Field(
        default="Long-term cost unclear - potential impact on health, productivity, or relationships.",
        description=(
            "What this habit is likely to damage over time if unchanged: health, career, relationships, self-respect, etc."
        ),
    )

    # ---- Legacy-style descriptive fields (kept OPTIONAL for compatibility) ----
    main_trigger: Optional[str] = Field(
        default=None,
        description="Short description of the most important trigger context, if identifiable.",
    )
    peak_times: Optional[str] = Field(
        default=None,
        description="When the habit is strongest, if relevant.",
    )
    common_locations: Optional[str] = Field(
        default=None,
        description="Where the habit usually happens, if relevant. Not all habits need a location.",
    )
    emotional_patterns: Optional[str] = Field(
        default=None,
        description="Key emotion patterns linked to the habit.",
    )
    frequency_pattern: Optional[str] = Field(
        default=None,
        description="Summary of how often and how intensely it happens.",
    )
    previous_attempts: Optional[str] = Field(
        default=None,
        description="What they've tried before and how it went.",
    )
    motivation_reason: Optional[str] = Field(
        default=None,
        description="Their main stated reasons for wanting change.",
    )
    risk_situations: Optional[str] = Field(
        default=None,
        description="Specific situations where harm or big negative consequences are most likely.",
    )

    # Optional extra human-readable summary of mechanism
    mechanism_summary: Optional[str] = Field(
        default=None,
        description="Short, clinician-style summary tying all the above into one coherent explanation.",
    )




# -------------------- 21-Day Plan -------------------- #

class DayTask(BaseModel):
    """
    A single task for a day.
    """
    title: str = Field(
        ...,
        description="Short task title (≤ 12 words)"
    )
    description: str = Field(
        ...,
        description="Detailed, clear task description that fully explains what to do (≤ 50 words)"
    )
    reason: str = Field(
        ...,
        description="Why this task matters - explain the purpose and how it helps with habit change (≤ 40 words)"
    )
    kind: str = Field(
        default="behavioral",
        description="Task type: behavioral, cognitive, environmental, identity, or reflection"
    )


class Plan21D(BaseModel):
    """
    21-day habit reduction plan.

    - day_tasks: 3-4 concrete tasks per day (short, behavioral).
    - day_whys: optional short explanations for *why* this day's tasks work
      (used for a 'Why this?' toggle in the UI).
    """
    plan_summary: str

    # e.g. {"day_1": [DayTask(...), DayTask(...), ...], "day_2": [...], ...}
    day_tasks: Dict[str, List[DayTask]]

    # e.g. {"day_1": "These tasks weaken the cue→reward link in your evening loop.", ...}
    day_whys: Optional[Dict[str, str]] = None



# -------------------- Global State -------------------- #

class HabitState(BaseModel):
    """
    Global state passed between LangGraph nodes.
    """

    # Identification / meta
    user_id: Optional[str] = None

    # Initial short description like: "I'm addicted to Zyn"
    habit_description: Optional[str] = None

    # AI-generated quiz
    quiz_form: Optional[QuizForm] = None

    # Structured quiz answers:
    #   {question_id: option_id}, e.g. {"q1": "q1_b", "q2": "q2_d"}
    # Backwards-compatible: if you still store a free-text string,
    # ai_nodes.quiz_summary_node will handle it.
    user_quiz_answers: Optional[Dict[str, str]] = None

    # LLM outputs
    safety: Optional[SafetyResult] = None
    quiz_summary: Optional[QuizSummary] = None
    plan21: Optional[Plan21D] = None

    # Coaching
    last_user_message: Optional[str] = None
    coach_reply: Optional[str] = None

    # Conversation history for the coach
    # Each message: {"role": "user" | "assistant", "content": "..."}
    chat_history: List[Dict[str, str]] = []

    # Optional routing field if you add routers later
    next: Optional[str] = None

    canonical_habit_name: Optional[str] = None
    canonical_confidence: Optional[str] = None
    last_why_day: Optional[str] = None
    last_why_explanation: Optional[str] = None
